<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SymSpell" Version="6.7.3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Correction/frequency_dictionary_en_82_765.txt">
      <LogicalName>frequency_dictionary_en_82_765.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
