<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sidekit.Core\Sidekit.Core.csproj" />
  </ItemGroup>

</Project>
